### ISSUE TITLE
Docker compose & some suggestions

### ISSUE THREAD

**Issue by heyitsforest** [Aadv1k/quillia#1]
(Copied from Reddit)

Love the style of this project! 
Currently to start using it I'd need:
- Self-hosted database (eg. PostgreSQL)
- Docker-compose example

A few suggestions (ordered by preference):
- Save page position in the reader per user
- Dark mode toggle
- Option to hide books to users not logged in (alternatively, set it for each book like Memos does)
- Option to import books from a server folder
- Search
- Sorting options (alphabetical, upload data, most issued)
- Account management - Sign out, delete account, delete books
- Upload book via link to epub (eg. Guthenburg/Oceanofpdf)

**Comment by Aadv1k** [comment]
Added a `docker-compose.yml` file that works. Let me know if you have any issues, I will be adding more features soon.

**Comment by Aadv1k** [comment]
Added functionality to delete a book and subsequent API and Front-End changes
